
@port = 9000
@url = http://localhost:{{port}}


###
GET {{url}}
content-type: application/json
###
DELETE {{url}}/deleteuser/6192364bd6ae00cce4e19db3
content-type: application/json

###
POST  {{url}}/adduser
content-type: application/json
 
{
    "user": {
        "name": "Giacomo",
        "username": "angie_additive",
        "email": "angie@hotmail.com"
    }
}

### update a user 
PATCH {{url}}/edituser/6192364bd6ae00cce4e19db5
content-type: application/json

{
    "email": "giacomo@dfdf"
    }